-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module StarWars.Mutation exposing (SendMessageRequiredArguments, increment, sendMessage)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import StarWars.Enum.Phrase
import StarWars.InputObject
import StarWars.Interface
import StarWars.Object
import StarWars.Scalar
import StarWars.ScalarCodecs
import StarWars.Union


increment : SelectionSet Int RootMutation
increment =
    Object.selectionForField "Int" "increment" [] Decode.int


type alias SendMessageRequiredArguments =
    { characterId : StarWars.ScalarCodecs.Id
    , phrase : StarWars.Enum.Phrase.Phrase
    }


sendMessage : SendMessageRequiredArguments -> SelectionSet decodesTo StarWars.Object.ChatMessage -> SelectionSet (Maybe decodesTo) RootMutation
sendMessage requiredArgs object_ =
    Object.selectionForCompositeField "sendMessage" [ Argument.required "characterId" requiredArgs.characterId (StarWars.ScalarCodecs.codecs |> StarWars.Scalar.unwrapEncoder .codecId), Argument.required "phrase" requiredArgs.phrase (Encode.enum StarWars.Enum.Phrase.toString) ] object_ (identity >> Decode.nullable)
