-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module StarWars.Object exposing (ChatMessage(..), Droid(..), Human(..))


type ChatMessage
    = ChatMessage


type Droid
    = Droid


type Human
    = Human
