-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module StarWars.ScalarCodecs exposing (Id, PosixTime, codecs)

import Json.Decode as Decode exposing (Decoder)
import StarWars.Scalar exposing (defaultCodecs)


type alias Id =
    StarWars.Scalar.Id


type alias PosixTime =
    StarWars.Scalar.PosixTime


codecs : StarWars.Scalar.Codecs Id PosixTime
codecs =
    StarWars.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecPosixTime = defaultCodecs.codecPosixTime
        }
