-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module StarWars.Object.ChatMessage exposing (character, phrase)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import StarWars.Enum.Phrase
import StarWars.InputObject
import StarWars.Interface
import StarWars.Object
import StarWars.Scalar
import StarWars.ScalarCodecs
import StarWars.Union


character : SelectionSet decodesTo StarWars.Interface.Character -> SelectionSet (Maybe decodesTo) StarWars.Object.ChatMessage
character object_ =
    Object.selectionForCompositeField "character" [] object_ (identity >> Decode.nullable)


phrase : SelectionSet StarWars.Enum.Phrase.Phrase StarWars.Object.ChatMessage
phrase =
    Object.selectionForField "Enum.Phrase.Phrase" "phrase" [] StarWars.Enum.Phrase.decoder
