-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module StarWars.Object.Droid exposing (appearsIn, avatarUrl, friends, id, name, primaryFunction)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import StarWars.Enum.Episode
import StarWars.InputObject
import StarWars.Interface
import StarWars.Object
import StarWars.Scalar
import StarWars.ScalarCodecs
import StarWars.Union


{-| Which movies they appear in.
-}
appearsIn : SelectionSet (List StarWars.Enum.Episode.Episode) StarWars.Object.Droid
appearsIn =
    Object.selectionForField "(List Enum.Episode.Episode)" "appearsIn" [] (StarWars.Enum.Episode.decoder |> Decode.list)


{-| Url to a profile picture for the character.
-}
avatarUrl : SelectionSet String StarWars.Object.Droid
avatarUrl =
    Object.selectionForField "String" "avatarUrl" [] Decode.string


{-| The friends of the droid, or an empty list if they have none.
-}
friends : SelectionSet decodesTo StarWars.Interface.Character -> SelectionSet (List decodesTo) StarWars.Object.Droid
friends object_ =
    Object.selectionForCompositeField "friends" [] object_ (identity >> Decode.list)


{-| The ID of the droid.
-}
id : SelectionSet StarWars.ScalarCodecs.Id StarWars.Object.Droid
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (StarWars.ScalarCodecs.codecs |> StarWars.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The name of the droid.
-}
name : SelectionSet String StarWars.Object.Droid
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| The primary function of the droid.
-}
primaryFunction : SelectionSet (Maybe String) StarWars.Object.Droid
primaryFunction =
    Object.selectionForField "(Maybe String)" "primaryFunction" [] (Decode.string |> Decode.nullable)
