-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module StarWars.Object.Human exposing (appearsIn, avatarUrl, friends, homePlanet, id, name)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import StarWars.Enum.Episode
import StarWars.InputObject
import StarWars.Interface
import StarWars.Object
import StarWars.Scalar
import StarWars.ScalarCodecs
import StarWars.Union


{-| Which movies they appear in.
-}
appearsIn : SelectionSet (List StarWars.Enum.Episode.Episode) StarWars.Object.Human
appearsIn =
    Object.selectionForField "(List Enum.Episode.Episode)" "appearsIn" [] (StarWars.Enum.Episode.decoder |> Decode.list)


{-| Url to a profile picture for the character.
-}
avatarUrl : SelectionSet String StarWars.Object.Human
avatarUrl =
    Object.selectionForField "String" "avatarUrl" [] Decode.string


{-| The friends of the human, or an empty list if they have none.
-}
friends : SelectionSet decodesTo StarWars.Interface.Character -> SelectionSet (List decodesTo) StarWars.Object.Human
friends object_ =
    Object.selectionForCompositeField "friends" [] object_ (identity >> Decode.list)


{-| The home planet of the human, or null if unknown.
-}
homePlanet : SelectionSet (Maybe String) StarWars.Object.Human
homePlanet =
    Object.selectionForField "(Maybe String)" "homePlanet" [] (Decode.string |> Decode.nullable)


{-| The ID of the human.
-}
id : SelectionSet StarWars.ScalarCodecs.Id StarWars.Object.Human
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (StarWars.ScalarCodecs.codecs |> StarWars.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The name of the human.
-}
name : SelectionSet String StarWars.Object.Human
name =
    Object.selectionForField "String" "name" [] Decode.string
